name: "Dev"

on:
  workflow_dispatch:
  push:
    branches-ignore: ["master"]
    paths:
      - ".github/workflows/dev.yaml"
      - ".vitepress/**"
      - "docs/**"
      - "package*.json"

# Debug 1

concurrency:
  group: dev
  cancel-in-progress: true

jobs:
  build:
    name: "Build"
    if: ${{ !contains(github.event.head_commit.message, '#nodev') }}
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
    with:
      name: "artifact"

  deploy:
    name: "Deploy"
    uses: cssnr/workflows/.github/workflows/deploy-static.yaml@master
    needs: build
    permissions:
      contents: read
    with:
      name: "dev"
      url: "https://dev-static.cssnr.com/github-projects"
      path: "github-projects"
      robots: true
      #artifact: "artifact"
      #dest: "/static"
    secrets:
      host: ${{ secrets.DEV_DEPLOY_HOST }}
      port: ${{ secrets.DEV_DEPLOY_PORT }}
      user: ${{ secrets.DEV_DEPLOY_USER }}
      pass: ${{ secrets.DEV_DEPLOY_PASS }}
      webhook: ${{ secrets.DISCORD_WEBHOOK }}
