name: "Pages"

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/pages.yaml"
      - ".vitepress/**"
      - "docs/**"
      - "package*.json"

env:
  crawler-id: ""
  purge-domain: ""

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: "Build"
    if: ${{ !contains(github.event.head_commit.message, '#nodeploy') }}
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
    with:
      pages: true

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "Deploy Pages"
        id: deployment
        uses: actions/deploy-pages@v4

      - name: "Send Deploy Notification"
        if: ${{ !cancelled() }}
        continue-on-error: true
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: ${{ steps.deployment.outputs.page_url }}

  post:
    name: "Post-Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: deploy

    steps:
      - name: "Purge Cache"
        if: ${{ env.purge-domain != '' }}
        uses: cssnr/cloudflare-purge-cache-action@v2
        with:
          zones: ${{ env.purge-domain }}
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: "Algolia Crawler"
        if: ${{ env.crawler-id != '' }}
        uses: cssnr/algolia-crawler-action@v1
        with:
          crawler_id: ${{ env.crawler-id }}
          crawler_user_id: ${{ secrets.CRAWLER_USER_ID }}
          crawler_api_key: ${{ secrets.CRAWLER_API_KEY }}

      - name: "Send Post-Deploy Notification"
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
